package zyh.JAVAadvanced.Exception.exar;

/**
 * \* Created with IntelliJ IDEA.
 * \* User: Javazyh
 * \* Date: 2019/7/5
 * \* Time: 18:18
 * \
 */
public class ReturnExceptionDemo {
//    static void methodA() {
//        try {
//            System.out.println("进入方法A");
//            throw new RuntimeException("制造异常");
//        } finally {
//            System.out.println("用A方法的finally");
//        }
//    }
//    static void methodB() {
//        try {
//            System.out.println("进入方法B");
//            return;
//        } finally {
//            System.out.println("调用B方法的finally");
//        }
//    }
//    public static void main(String[] args) {
//        try {
//            methodA();
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//            e.printStackTrace();
//        }
//        methodB();
//    }

}
